name: ${PROJECT_NAME}

services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "${NGINX_PORT}:80"
      - "${VITE_PORT}:${VITE_PORT}"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

networks:
  app-network:
    driver: bridge
