# $schema: https://json.schemastore.org/github-workflow.json

name: Building

on:
  workflow_call:

env:
  ENV_MODE: production

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./frontend
          tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}-frontend:latest

      - name: Notify Telegram on Failure
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Build
          title: ❌ Build Failure ❌
          to: ${{ secrets.TELEGRAM_NOTIFIER_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFIER_BOT_TOKEN }}
